update1

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -66,9 +66,13 @@ jobs:
       - name: Bazel Build
         run: |
           bazel build --lockfile_mode=error --config ${{ matrix.bazel-config }} -- ${{ matrix.bazel-build-target }}
+          if git diff HEAD~1 HEAD | grep -q "MODULE.bazel"; then
+             if !(git diff  HEAD~1 HEAD | grep -q  "MODULE.bazel.lock"); then
+                echo "::error::MODULE.bazel.lock is changed"
+                exit 10
       - name: Bazel Test
         run: |
-          bazel test --lockfile_mode=erro --config ${{ matrix.bazel-config }} ${{ matrix.bazel-test-extra-flags }} -- ${{ matrix.bazel-test-target }}
+          bazel test --lockfile_mode=error --config ${{ matrix.bazel-config }} ${{ matrix.bazel-test-extra-flags }} -- ${{ matrix.bazel-test-target }}
       - name: Upload test logs on failure
         if: failure()
         uses: actions/upload-artifact@v7
